@{
RootModule = 'PSSysmonTools.psm1'

ModuleVersion = '0.1.0.0'

GUID = '0f91cb8e-56b8-44c2-821c-bab1ad7c369a'

Author = 'Matthew Graeber'

Copyright = 'BSD 3-Clause'

Description = 'A module for working with Sysinternals Sysmon.'

PowerShellVersion = '3.0'

# Functions to export from this module
FunctionsToExport = @(
    'Get-SysmonConfiguration',
    'ConvertFrom-SysmonBinaryConfiguration',
    'Test-SysmonConfiguration'
)

PrivateData = @{

    PSData = @{
        Tags = @('security', 'DFIR', 'defense')

        LicenseUri = 'https://github.com/mattifestation/PSSysmonTools/blob/master/LICENSE'

        ProjectUri = 'https://github.com/mattifestation/PSSysmonTools'

        ReleaseNotes = @'
0.1.0
-----
Enhancements:
* PSSysmonTools is now a proper PowerShell module.
* Added Get-SysmonConfiguration, ConvertFrom-SysmonBinaryConfiguration, Test-SysmonConfiguration
* Added a Sysmon 3.4 configuration schema in the Schemas directory
* Added a mostly autogenerated 3.4 schema instance to Tests\SampleConfigs\Sysmon_3_40_Autogenerated.xml
'@
    }

}

}
